# Predicting Whether a Customer Will Purchase (Yes / No)

### Business Context 

An e-commerce company wants to predict whether a customer will make a purchase based on:
1. How many minutes they spent on the website
2. How many pages they viewed
3. Whether they came via an ad campaign
4. Their age

This is a binary classification problem:

1 = Customer purchased

0 =  Customer did NOT purchase

This makes it a  Logistic Regression Problem

### Objective

Build a Logistic Regression model that predicts:
Will the customer purchase? (Yes = 1 / No = 0)

### Step 1: Create the Dataset

In [1]:
import pandas as pd

# Create dataset
data = {
    'time_on_site': [5, 10, 3, 20, 15, 2, 25, 18, 7, 30],
    'pages_viewed': [2, 5, 1, 10, 8, 1, 12, 9, 3, 15],
    'ad_click':     [0, 1, 0, 1, 1, 0, 1, 1, 0, 1],
    'age':          [22, 35, 19, 45, 38, 21, 50, 42, 25, 55],
    'purchased':    [0, 1, 0, 1, 1, 0, 1, 1, 0, 1]
}

df = pd.DataFrame(data)
df

,time_on_site,pages_viewed,ad_click,age,purchased
0,5,2,0,22,0
1,10,5,1,35,1
2,3,1,0,19,0
3,20,10,1,45,1
4,15,8,1,38,1
5,2,1,0,21,0
6,25,12,1,50,1
7,18,9,1,42,1
8,7,3,0,25,0
9,30,15,1,55,1


### Step 2: Understand the Data

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   time_on_site  10 non-null     int64
 1   pages_viewed  10 non-null     int64
 2   ad_click      10 non-null     int64
 3   age           10 non-null     int64
 4   purchased     10 non-null     int64
dtypes: int64(5)
memory usage: 532.0 bytes


In [3]:
df.describe()

,time_on_site,pages_viewed,ad_click,age,purchased
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,13.500000,6.600000,0.600000,35.200000,0.600000
std,9.652288,4.926121,0.516398,12.925427,0.516398
min,2.000000,1.000000,0.000000,19.000000,0.000000
25%,5.500000,2.250000,0.000000,22.750000,0.000000
50%,12.500000,6.500000,1.000000,36.500000,1.000000
75%,19.500000,9.750000,1.000000,44.250000,1.000000
max,30.000000,15.000000,1.000000,55.000000,1.000000


### Step 3: Define X (features) and y (target)
### Step 4: Train–Test Split

In [6]:
X = df[['time_on_site', 'pages_viewed', 'ad_click', 'age']]
y = df['purchased']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

### Step 5: Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Step 6: Train Logistic Regression Model

In [11]:

from sklearn.linear_model import LogisticRegression 

model = LogisticRegression()
model.fit(X_train_scaled, y_train)


LogisticRegression()

### Step 7: Make Predictions

In [13]:
# 1️⃣ Class predictions (0 or 1)

y_pred = model.predict(X_test_scaled)
y_pred


array([0, 1, 0])

In [14]:
# 2️⃣ Probability predictions (THIS IS LOGISTIC MAGIC)

y_prob = model.predict_proba(X_test_scaled)
y_prob

array([[0.76126293, 0.23873707],
       [0.2304623 , 0.7695377 ],
       [0.861066  , 0.138934  ]])

### Step 8: Model Evaluation

In [15]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[2, 0],
       [0, 1]])

### Accuracy

In [16]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

1.0

In [17]:
# Classification Report

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



### Step 9: Understand the Model Coefficients

In [18]:
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

coefficients

,Feature,Coefficient
0,time_on_site,0.493289
1,pages_viewed,0.523377
2,ad_click,0.700246
3,age,0.542994


How to interpret:

Positive coefficient → increases probability of purchase

Negative coefficient → decreases probability

Example:

If time_on_site coefficient = +1.2
→ More time on site → higher chance of purchase

### Step 10: Interpret Using Odds

In [19]:
import numpy as np

coefficients['Odds_Ratio'] = np.exp(coefficients['Coefficient'])
coefficients

,Feature,Coefficient,Odds_Ratio
0,time_on_site,0.493289,1.637693
1,pages_viewed,0.523377,1.687717
2,ad_click,0.700246,2.014248
3,age,0.542994,1.721152


Interpretation:

Odds Ratio > 1 → increases odds

Odds Ratio < 1 → decreases odds

### Step 11: Predict for a New Customer

In [20]:
new_customer = pd.DataFrame({
    'time_on_site': [12],
    'pages_viewed': [6],
    'ad_click': [1],
    'age': [32]
})

new_customer_scaled = scaler.transform(new_customer)

model.predict(new_customer_scaled)
model.predict_proba(new_customer_scaled)

array([[0.21491422, 0.78508578]])